import customButtonPlugin from './src/assets/styles/tailwind-custom-button';
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#3aafa9",
        "primary-dark": "#2b7a78",
        "primary-light": "#def2f1",
        "dark": "#17252a",
        "medium": "#9f9f9f",
        "light": "#afafaf",
        "completed":"#dcfce7",
        "completed-dark":"#16a34a",
        "inProgress":"#e0f2fe",
        "inProgress-dark":"#0369a1",
        "onHold": "#fef3c7",         
        "onHold-dark": "#f59e0b",  
        "cancelled": "#fee2e2",      
        "cancelled-dark": "#b91c1c",  
        "toDo": "#f3f4f6",           
        "toDo-dark": "#6b7280",    
        "blocked": "#fde8e8",        
        "blocked-dark": "#c53030", 
        "pendingReview": "#fef9c3",  
        "pendingReview-dark": "#d97706",  
        "open": "#e0f7fa",          
        "open-dark": "#0288d1",    
        "closed": "#e0f2f1",        
        "closed-dark": "#00695c", 
        "answered": "#e0ffe4",      
        "answered-dark": "#2e7d32", 
        "waiting": "#e3f2fd",        
        "waiting-dark": "#1e40af", 
        "notAnswered": "#fce4ec",    
        "notAnswered-dark": "#ad1457",  
        "high": "#f8d7da",          
        "high-dark": "#c53030",    
        "low": "#f1f8e9",           
        "low-dark": "#388e3c",     
        "medium": "#fff3e0",        
        "medium-dark": "#ef6c00",  
        "notStarted": "#f3f4f6",    
        "notStarted-dark": "#4b5563", 
        "warning": "#fff8c5",        
        "warning-dark": "#d97706",
        "danger": "#fee2e2",     
        "danger-dark": "#b91c1c",  
        "info": "#bfdbfe",      
        "info-dark": "#2563eb",    
        "success": "#d1fae5",       
        "success-dark": "#16a34a", 
        "fail": "#fca5a5",     
        "fail-dark": "#dc2626",    
        "error": "#fde2e2",     
        "error-dark": "#b91c1c", 
        "active": "#d1fae5",   
        "active-dark": "#16a34a",  
        "notActive": "#fca5a5",  
        "notActive-dark": "#dc2626", 
      }
    },
  },
  plugins: [
    customButtonPlugin  
  ], 
}